version: '3.3'
services:
  php7:
    build: ./.docker/php7
    restart: always
    env_file:
      - .env
    volumes:
      - ~/.composer:/root/.composer
      - .:/app
    environment:
       XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWD}
    volumes:
      - ./.docker/volumes/postgres/dump/:/docker-entrypoint-initdb.d/
      - ./.docker/volumes/postgres/data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
